# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ip-pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - start: "${CILIUM_ADDRESS_START}"
      stop: "${CILIUM_ADDRESS_STOP}"
