apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - secret.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml

configMapGenerator:
  - name: homepage-config-files
    namespace: homepage
    files:
      - configs/kubernetes.yaml
      - configs/settings.yaml
      - configs/custom.css
      - configs/custom.js
      - configs/bookmarks.yaml
      - configs/services.yaml
      - configs/widgets.yaml
      - configs/docker.yaml
