# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.33.0/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: blocky-service
  namespace: blocky
spec:
  type: LoadBalancer
  loadBalancerIP: "${BLOCKY_GATEWAY_ADDRESS}"
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    app: blocky
