# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: snapshot-controller
      version: "0.3.0"
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
  values:
    # Defaults are pretty sane!
