# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: democratic-csi
spec:
  interval: 24h
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"

    driver:
      config:
        driver: freenas-iscsi
        httpConnection:
          protocol: https
          apiKey: "${SECRET_TRUENAS_API_KEY}"
          host: "${SECRET_TRUENAS_HOST}"
          port: 443
          allowInsecure: true
        sshConnection:
          host: "${SECRET_TRUENAS_HOST}"
          username: "${SECRET_TRUENAS_USER}"
          password: "${SECRET_TRUENAS_PASS}"
        zfs:
          cli:
            sudoEnabled: true
            paths:
              chroot: /sbin/chroot
              sudo: /usr/bin/sudo
              zfs: /sbin/zfs
              zpool: /sbin/zpool
          datasetParentName: tank/iscsi/vols
          detachedSnapshotsDatasetParentName: tank/iscsi/snaps
          zvolCompression: ""
          zvolDedup: ""
          zvolEnableReservation: false
          zvolBlocksize: 4k
        iscsi:
          targetPortal: "${SECRET_TRUENAS_PORTAL_1}"
          # 2025-08-28: Multipath is not ready right now
          # targetPortals:
          #   - "${SECRET_TRUENAS_PORTAL_1}"
          #   - "${SECRET_TRUENAS_PORTAL_2}"
          interface: ""
          namePrefix: "csi-"
          nameSuffix: ""
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
              targetGroupAuthGroup: ""
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: "SSD"
          extentAvailThreshold: 0

    storageClasses:
      - name: truenas-iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    volumeSnapshotClasses:
      - name: truenas-iscsi
        parameters:
          detachedSnapshots: "true"

    controller:
      driver:
        image:
          tag: next

    node:
      hostPID: true
      driver:
        # There is no way this works and pulls in the "next" docker image,
        # which supports TrueNAS 25+
        image:
          tag: next
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        # https://github.com/siderolabs/extensions/issues/688
        # iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ""
