- kubernetes:
    cluster:
      show: true
      cpu: false
      memory: false
      showLabel: true
      label: "hardwood"
    nodes:
      show: true
      cpu: false
      memory: false
      showLabel: true
# already get resource usage from cluster above
# - resources:
#     backend: resources
#     expanded: true
#     cpu: true
#     memory: true
#     network: default
- search:
    provider: duckduckgo
    target: self
