apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  CILIUM_ADDRESS_START: "10.100.10.32"
  CILIUM_ADDRESS_STOP: "10.100.10.243"
  CILIUM_HTTP_GATEWAY_ADDRESS: "10.100.10.33"
  LETS_ENCRYPT_SERVER: "https://acme-v02.api.letsencrypt.org/directory"
