- alias: Outside Lights at Sunset
  description: ""
  mode: single
  triggers:
    - trigger: sun
      event: sunset
      offset: 0
  conditions: []
  actions:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.outside_lights_on
- alias: Outside Lights at Sunrise
  description: ""
  mode: single
  triggers:
    - trigger: sun
      event: sunrise
      offset: 0
  conditions: []
  actions:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.outside_lights_off
- alias: Headboard Light Switch On
  description: ""
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - event.remote_switch_29122_scene_001
      attribute: event_type
      to: KeyPressed
  conditions: []
  actions:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- alias: Headboard Light Switch Off
  description: ""
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - event.remote_switch_29122_scene_002
      attribute: event_type
      to: KeyPressed
  conditions: []
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- alias: Headboard Light Time On
  description: ""
  mode: single
  triggers:
    - trigger: time
      at: "20:00:00"
  conditions: []
  actions:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- alias: Headboard Light Time Off
  description: ""
  mode: single
  triggers:
    - trigger: time
      at: "22:30:00"
  conditions: []
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- alias: Notify TV of Person at Front Door
  description: ""
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.doorbell_person_detected
      from: "off"
      to: "on"
  actions:
    - action: camera.snapshot
      target:
        entity_id: camera.doorbell_low_resolution_channel
      data:
        filename: /config/snap.doorbell.jpg
    - action: notify.google_streamer
      data:
        title: Person Detected
        message: Front Door
        data:
          image: /config/snap.doorbell.jpg
