- id: 01K46117CFTS4X23TECS5KE88R
  alias: Outside Lights at Sunset
  description: ""
  mode: single
  triggers:
    - trigger: sun
      event: sunset
      offset: 0
  conditions: []
  actions:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.outside_lights_on
- id: 01K46117CFQV3HJTT7DS83K301
  alias: Outside Lights at Sunrise
  description: ""
  mode: single
  triggers:
    - trigger: sun
      event: sunrise
      offset: 0
  conditions: []
  actions:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.outside_lights_off
- id: 01K46117CF5KT7CY6408ARBM30
  alias: Headboard Light Switch On
  description: ""
  mode: single
  triggers:
    - device_id: 717656b0febf0d6f1f82cc5180f9faef
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "001"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 001
      trigger: device
      value: 0
  conditions: []
  actions:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- id: 01K46117CFE170Z294MW11QZAE
  alias: Headboard Light Switch Off
  description: ""
  mode: single
  triggers:
    - device_id: 717656b0febf0d6f1f82cc5180f9faef
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "002"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 002
      trigger: device
      value: 0
  conditions: []
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- id: 01K46117CFAZP9P154W96QT1S9
  alias: Headboard Light Time On
  description: ""
  mode: single
  triggers:
    - trigger: time
      at: "20:00:00"
  conditions: []
  actions:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- id: 01K46117CF9Y3M1WW4ECCF045C
  alias: Headboard Light Time Off
  description: ""
  mode: single
  triggers:
    - trigger: time
      at: "22:30:00"
  conditions: []
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- id: 01K46117CFC7Q3BDJXGS4ZXZKG
  alias: Notify TV of Person at Front Door
  description: ""
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.doorbell_person_detected
      from: "off"
      to: "on"
  actions:
    - action: camera.snapshot
      target:
        entity_id: camera.doorbell_low_resolution_channel
      data:
        filename: /config/snap.doorbell.jpg
    - action: notify.google_streamer
      data:
        title: Person Detected
        message: Front Door
        data:
          image: /config/snap.doorbell.jpg
- id: 01K48HM9SCAWERE815C2B16JX4
  alias: Notify TV of Vehicle on Driveway
  description: ""
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.driveway_vehicle_detected
      from: "off"
      to: "on"
  actions:
    - action: camera.snapshot
      target:
        entity_id: camera.driveway_low_resolution_channel
      data:
        filename: /config/snap.driveway.jpg
    - action: notify.google_streamer
      data:
        title: Vehicle Detected
        message: Driveway
        data:
          image: /config/snap.driveway.jpg
- id: 01K48W984P7E5E8FEZS9PFHCY5
  alias: Switch On Basement Lights
  description: ""
  mode: single
  triggers:
    - device_id: d5690c3114d77b70fa4f00b4602611ad
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "001"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 001
      trigger: device
      value: 3
    - device_id: e6c30c92fb3c926b91d1241750125a08
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "001"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 001
      trigger: device
      value: 3
    - device_id: 45ac941ff59d752fc3e82409bd6f5c56
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "001"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 001
      trigger: device
      value: 3
  conditions: []
  actions:
    - type: turn_on
      device_id: d5690c3114d77b70fa4f00b4602611ad
      entity_id: 044f983c87b6d1af7afbf61083e1ac6a
      domain: switch
    - type: turn_on
      device_id: e6c30c92fb3c926b91d1241750125a08
      entity_id: fdfa070910f3b753aed371b868f80a83
      domain: switch
    - type: turn_on
      device_id: 45ac941ff59d752fc3e82409bd6f5c56
      entity_id: da179915a7717f0c58b6072b8a15778d
      domain: switch
- id: 01K48W984PFTJ8YHB769QB3CG8
  alias: Switch Off Basement Lights
  description: ""
  mode: single
  triggers:
    - device_id: d5690c3114d77b70fa4f00b4602611ad
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "002"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 002
      trigger: device
      value: 3
    - device_id: e6c30c92fb3c926b91d1241750125a08
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "002"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 002
      trigger: device
      value: 3
    - device_id: 45ac941ff59d752fc3e82409bd6f5c56
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "002"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 002
      trigger: device
      value: 3
  conditions: []
  actions:
    - type: turn_off
      device_id: d5690c3114d77b70fa4f00b4602611ad
      entity_id: 044f983c87b6d1af7afbf61083e1ac6a
      domain: switch
    - type: turn_off
      device_id: e6c30c92fb3c926b91d1241750125a08
      entity_id: fdfa070910f3b753aed371b868f80a83
      domain: switch
    - type: turn_off
      device_id: 45ac941ff59d752fc3e82409bd6f5c56
      entity_id: da179915a7717f0c58b6072b8a15778d
      domain: switch
- id: 01K5NWANZW5RDHJ34CNX3C6J7E
  alias: "Halloween lights on at sunset, 5am"
  description: "Halloween lights on at sunset, 5am"
  mode: single
  triggers:
    - trigger: sun
      event: sunset
      offset: "-1:00:00"
    - trigger: time
      at: "05:00:00"
  conditions: []
  actions:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        device_id:
          - 42d52e39eda6946dbf1b72ad2cccd4ad
          - 62ae530718c8fab5da0b2edd929aee45
- id: 01K5NWANZW4MGMZYDSD0AM9H73
  alias: "Halloween lights off at sunrise, 8pm"
  description: "Halloween lights off at sunrise, 8pm"
  mode: single
  triggers:
    - trigger: sun
      event: sunrise
      offset: 0
    - trigger: time
      at: "20:00:00"
  conditions: []
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        device_id:
          - 42d52e39eda6946dbf1b72ad2cccd4ad
          - 62ae530718c8fab5da0b2edd929aee45
