- id: 01K46117CFTS4X23TECS5KE88R
  alias: Outside Lights at Sunset
  description: ""
  mode: single
  triggers:
    - trigger: sun
      event: sunset
      offset: 0
  conditions: []
  actions:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.outside_lights_on
- id: 01K46117CFQV3HJTT7DS83K301
  alias: Outside Lights at Sunrise
  description: ""
  mode: single
  triggers:
    - trigger: sun
      event: sunrise
      offset: 0
  conditions: []
  actions:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.outside_lights_off
- id: 01K46117CF5KT7CY6408ARBM30
  alias: Headboard Light Switch On
  description: ""
  mode: single
  triggers:
    - device_id: 717656b0febf0d6f1f82cc5180f9faef
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "001"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 001
      trigger: device
      value: 0
  conditions: []
  actions:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- id: 01K46117CFE170Z294MW11QZAE
  alias: Headboard Light Switch Off
  description: ""
  mode: single
  triggers:
    - device_id: 717656b0febf0d6f1f82cc5180f9faef
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "002"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 002
      trigger: device
      value: 0
  conditions: []
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- id: 01K46117CFAZP9P154W96QT1S9
  alias: Headboard Light Time On
  description: ""
  mode: single
  triggers:
    - trigger: time
      at: "20:00:00"
  conditions: []
  actions:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- id: 01K46117CF9Y3M1WW4ECCF045C
  alias: Headboard Light Time Off
  description: ""
  mode: single
  triggers:
    - trigger: time
      at: "22:30:00"
  conditions: []
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.mini_plug_59952
- id: 01K46117CFC7Q3BDJXGS4ZXZKG
  alias: Notify TV of Person at Front Door
  description: ""
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.doorbell_person_detected
      from: "off"
      to: "on"
  actions:
    - action: camera.snapshot
      target:
        entity_id: camera.doorbell_low_resolution_channel
      data:
        filename: /config/snap.doorbell.jpg
    - action: notify.google_streamer
      data:
        title: Person Detected
        message: Front Door
        data:
          image: /config/snap.doorbell.jpg
