# Secret test: ${SECRET_HA_TEST}
default_config:

homeassistant:
  allowlist_external_dirs:
    - "/config"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.0/16

# frontend:
#   themes: !include_dir_merge_named themes

automation: !include automations.yaml
scene: !include scenes.yaml
# script: !include scripts.yaml
# sensor: !include sensors.yaml
