# Secret test: ${SECRET_HA_TEST}
default_config:

homeassistant:
  allowlist_external_dirs:
    - "/conifg"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.0/16

automation: !include automations.yaml
scene: !include scenes.yaml
