- unique_id: 01K4JWMHXMSVP5T4Z28KTC9BJG
  trigger:
    - platform: time_pattern
      minutes: 1
  action:
    - service: calendar.get_events
      data:
        duration:
          start_date_time: "{{ now().strftime('%Y-%m-%d 00:00:00') }}"
          end_date_time: "{{ (now() + timedelta(days=7)).strftime('%Y-%m-%d 00:00:00') }}"
      target:
        entity_id: calendar.jbarkee
      response_variable: agenda
  sensor:
    - unique_id: 01K4MER28A1W84EM3X2VEJH9JX
      name: Jake & Bre Calendar
      state: "{{ agenda['calendar.jbarkee'].events | join('|', attribute='start') }}"
      attributes:
        agenda: |
          {% for event in agenda["calendar.jbarkee"].events %}
            {{- (event.start|as_datetime|as_local).strftime("%H:%M") }}: {{ event.summary }}<br>
          {% endfor %}
# Google AI generated:
- trigger:
    - platform: time_pattern
      minutes: 1
  action:
    - service: calendar.get_events
      data:
        duration:
          days: 7 # Get events for the next 7 days
        target:
          entity_id: calendar.jbarkee
        response_variable: upcoming_events
  sensor:
    - name: My Calendar Upcoming Events
      state: "{{ now() }}" # State can be anything, like current timestamp
      attributes:
        events: |
          {% for event in upcoming_events['calendar.jbarkee']['events'] %}
          - Summary: {{ event.summary }}
            Start: {{ (event.start|as_datetime|as_local).strftime("%Y-%m-%d %H:%M") }}
          {% endfor %}
