---
apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  interval: 24h
  url: https://democratic-csi.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: snapshot-controller
      version: "0.3.0"
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
  values:
    # Defaults are pretty sane!
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: democratic-csi
spec:
  interval: 24h
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"

    driver:
      config:
        driver: freenas-iscsi
        httpConnection:
          protocol: https
          apiKey: "${SECRET_TRUENAS_API_KEY}"
          host: "${SECRET_TRUENAS_HOST}"
          port: 443
          allowInsecure: true
        sshConnection:
          host: "${SECRET_TRUENAS_HOST}"
          username: "${SECRET_TRUENAS_USER}"
          password: "${SECRET_TRUENAS_PASS}"
        zfs:
          cli:
            sudoEnabled: true
          datasetParentName: tank/iscsi/vols
          detachedSnapshotsDatasetParentName: tank/iscsi/snaps
          zvolCompression: ""
          zvolDedup: ""
          zvolEnableReservation: false
          zvolBlocksize: 4k
        iscsi:
          targetPortals:
            - "${SECRET_TRUENAS_PORTAL_1}"
            - "${SECRET_TRUENAS_PORTAL_2}"
          interface: ""
          namePrefix: "csi-"
          nameSuffix: ""
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
              targetGroupAuthGroup: ""
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: "SSD"
          extentAvailThreshold: 0

    storageClasses:
      - name: truenas-iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    volumeSnapshotClasses:
      - name: truenas-iscsi
        parameters:
          detachedSnapshots: "true"

    controller:
      driver:
        image:
          tag: next

    node:
      hostPID: true
      driver:
        # There is no way this works and pulls in the "next" docker image,
        # which supports TrueNAS 25+
        image:
          tag: next
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        # https://github.com/siderolabs/extensions/issues/688
        # iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ""
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
  namespace: democratic-csi
spec:
  interval: 24h
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"

    driver:
      config:
        driver: freenas-nfs
        httpConnection:
          protocol: https
          apiKey: "${SECRET_TRUENAS_API_KEY}"
          host: "${SECRET_TRUENAS_HOST}"
          port: 443
          allowInsecure: true
        sshConnection:
          host: "${SECRET_TRUENAS_HOST}"
          username: "${SECRET_TRUENAS_USER}"
          password: "${SECRET_TRUENAS_PASS}"
        zfs:
          cli:
            sudoEnabled: true
          datasetParentName: tank/nfs/vols
          detachedSnapshotsDatasetParentName: tank/nfs/snaps
          zvolEnableQuotas: true
          zvolEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: "${SECRET_TRUENAS_HOST}"
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""

    storageClasses:
      - name: truenas-nfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - nfsvers=4

    volumeSnapshotClasses:
      - name: truenas-nfs
