---
apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  interval: 24h
  url: https://democratic-csi.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: snapshot-controller
      version: "0.3.0"
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
  values:
    # Defaults are pretty sane!
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: democratic-csi
spec:
  interval: 24h
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
  values:
    driver: freenas-iscsi
    instance_id: ""
    csiDriver:
      name: democratic-csi-iscsi
    sshConnection:
      host: "${SECRET_TRUENAS_HOST}"
      username: "${SECRET_TRUENAS_USER}"
      privateKey: "${SECRET_TRUENAS_PRIVATE_KEY}"
    zfs:
      cli:
        sudoEnabled: true
      datasetParentName: tank/iscsi/vols
      detachedSnapshotDatasetParentName: tank/iscsi/snaps
      zvolCompression: ""
      zvolDedup: ""
      zvolEnableReservation: false
      zvolBlocksize: 4k
    iscsi:
      targetPortals:
        - "${SECRET_TRUENAS_HOST}:3260"
      interface: ""
      namePrefix: "csi-"
      nameSuffix: ""
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
          targetGroupAuthGroup: ""
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
