# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.33.0/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wakapi
  namespace: wakapi
  labels:
    app: wakapi
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wakapi
  template:
    metadata:
      labels:
        app: wakapi
    spec:
      containers:
        - name: wakapi
          image: "ghcr.io/muety/wakapi:2.15.0"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          env:
            - name: WAKAPI_PASSWORD_SALT
              value: "${SECRET_WAKAPI_PASSWORD_SALT}"
            - name: WAKAPI_LISTEN_IPV4
              value: "0.0.0.0"
            - name: WAKAPI_PORT # https://github.com/muety/wakapi/issues/567#issuecomment-1842610636
              value: "3000"
            - name: WAKAPI_PUBLIC_URL
              value: "https://waka.${SECRET_DOMAIN}"
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - mountPath: /data
              name: wakapi-data
      volumes:
        - name: wakapi-data
          persistentVolumeClaim:
            claimName: wakapi-data
