# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/refs/heads/main/kustomization-kustomize-v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml

commonLabels:
  app.kubernetes.io/name: home-assistant
  app: home-assistant

configMapGenerator:
  - name: home-assistant-config-files
    namespace: home-assistant
    files:
      - configs/automations.yaml
      - configs/configuration.yaml
      - configs/scenes.yaml
      - configs/sensors.yaml
      - configs/templates.yaml
  - name: home-assistant-config-env
    namespace: home-assistant
    literals:
      - TZ="America/New_York"

configurations:
  - kustomizeconfig.yaml
