# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.33.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
  namespace: cloudflared
type: Opaque
data:
  token: "${SECRET_CLOUDFLARE_TUNNEL_TOKEN_BASE64}"
